# prettyboot theme: mac-light
banner themes/mac-light/background.png
banner_scale fillscreen
icons_dir themes/mac-light/icons
selection_big themes/mac-light/selection_big.png
selection_small themes/mac-light/selection_small.png
big_icon_size 128
small_icon_size 48
