# prettyboot theme: mac-dark
banner themes/mac-dark/background.png
banner_scale fillscreen
icons_dir themes/mac-dark/icons
selection_big themes/mac-dark/selection_big.png
selection_small themes/mac-dark/selection_small.png
big_icon_size 128
small_icon_size 48
